version: '3.9'

services:
  db:
    image: postgres
    container_name: job_connect_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: job_connect_db
    ports:
      - '5432:5432'
    restart: unless-stopped