spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/job_connect_db
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secretKey: GXnbt0cB7t0K7SJM2QCJGsNJjF818xxm
      expiration: 86400000

server:
  servlet:
    context-path: /api/v1/
#springdoc:
#  api-docs:
#    path: "/swagger/swagger-ui.html"
#
